"""Run the v1 baseline prompt and keep whatever comes back.

The README claims v1 fails for specific reasons. This runs it so the claim is evidence
rather than argument.

Deliberately unfair in only one direction: it uses the **same model** as the production
path, so the only variable is the prompt. v1 gets the raw CSV and asks for a briefing; v2
gets a computed fact pack and asks for prose. If v1's figures are wrong, the prompt is why.

    python scripts/run_v1_baseline.py

Writes `prompts/v1_baseline_output.md`. Needs GEMINI_API_KEY or ANTHROPIC_API_KEY.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.narrative import load_dotenv  # noqa: E402
from src.providers import GeminiProvider, ProviderError, _post_json  # noqa: E402


def main() -> int:
    load_dotenv()

    import os

    key = os.environ.get("GEMINI_API_KEY")
    if not key:
        print("GEMINI_API_KEY is not set.", file=sys.stderr)
        return 1

    prompt = (REPO_ROOT / "prompts" / "v1_baseline.md").read_text(encoding="utf-8")
    # The file carries its own critique below the prompt; send only the prompt itself.
    prompt = prompt.split("---\n\n## Why this fails")[0]
    prompt = prompt.split("---", 2)[-1].strip()

    data = (REPO_ROOT / "data" / "mock_sales.csv").read_text(encoding="utf-8").strip()
    filled = prompt.replace("{{DATA}}", data)

    model = GeminiProvider.info.model
    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{model}:generateContent?key={key}"
    )

    print(f"Running v1 against {model} — same model as the production path.")
    try:
        response = _post_json(
            url,
            {"contents": [{"role": "user", "parts": [{"text": filled}]}]},
            {"content-type": "application/json"},
        )
    except ProviderError as exc:
        print(f"Failed: {exc}", file=sys.stderr)
        return 1

    parts = response["candidates"][0].get("content", {}).get("parts") or []
    text = "".join(p.get("text", "") for p in parts)

    out = REPO_ROOT / "prompts" / "v1_baseline_output.md"
    out.write_text(
        "<!-- Generated by scripts/run_v1_baseline.py. Committed as evidence, not as a\n"
        "     deliverable. This is what the naive prompt produces; see CHANGELOG.md for\n"
        f"     what it got wrong. Model: {model}, the same one the production path uses. -->\n\n"
        + text,
        encoding="utf-8",
        newline="\n",
    )
    print(f"Wrote {out.relative_to(REPO_ROOT)} ({len(text.split())} words)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
